name: PR Title Check

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  title-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v4
        with:
          # Enforces conventional commit style in the PR title
          prTitle: ${{ github.event.pull_request.title }}
